name: Deploy
concurrency:
  group: deploy
  cancel-in-progress: true

on:
  workflow_call:
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout definitions
        uses: actions/checkout@v4
        with:
          ref: definitions

      - name: Checkout static files
        uses: actions/checkout@v4
        with:
          ref: generated
          path: generated

      - name: Clear .git folders (no submodules here!)
        run: |
          rm -rf .git
          rm -rf generated/.git
  
      - name: Put static files in place
        run: |
          cp -r generated/* ./
          rm -rf generated
      
      - name: Prepare for GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: deploy
          build_dir: "."
          jekyll: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
