name: Push main

on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: push
  cancel-in-progress: true

jobs:
  definitions:
    uses: ./.github/workflows/definitions.yml
    secrets: inherit

  deploy:
    needs: [definitions]
    if: always() && needs.definitions.result == 'success'
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    
  cleanup:
    needs: deploy
    if: always()
    uses: ./.github/workflows/cleanup.yml
    secrets: inherit
